framework:
    messenger:
        transports:
            scheduler-transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                
        routing:
            App\Scheduler\SendEmailMessage: scheduler-transport