vich_uploader:
    db_driver: orm

    mappings:
        video_games_covers:
            uri_prefix: /images/covers
            upload_destination: '%kernel.project_dir%/public/images/covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true